import { I18nTypes } from '@/packages/common/constants'

import toolsCodeMap from './pdfToolsCodeMap.json'

export type IToolUrkKeyType =
  | 'pdf-to-png'
  | 'pdf-to-jpeg'
  | 'merge-pdf'
  | 'split-pdf'
  | 'png-to-pdf'
  | 'jpeg-to-pdf'
  | 'heic-to-pdf'
  | 'pdf-to-html'
  | 'sign-pdf'
  | 'compress-pdf'
  | 'ocr-pdf'
  | 'number-pages'
  | 'rotate-pdf'
export interface IToolData {
  icon: string
  title: string
  description: string
  secondaryDescription: string //进入页面后的提示
  urlKey: IToolUrkKeyType
  urlPrefixPath?: string
  accept?: string
}
const routerChildrenObject = toolsCodeMap.childrenObject as {
  [key in IToolUrkKeyType]: IToolUrkKeyType
}
const toolsTopUrlKey = toolsCodeMap.topUrlKey
export const toolsObjectData: { [key in IToolUrkKeyType]: IToolData } = {
  'merge-pdf': {
    icon: 'MergePDF',
    title: 'pages:tools__index_page__constant_obj__merge_pdf__title',
    description:
      'pages:tools__index_page__constant_obj__merge_pdf__main_description',
    secondaryDescription:
      'pages:tools__index_page__constant_obj__merge_pdf__secondary_description',
    urlKey: routerChildrenObject['merge-pdf'],
    urlPrefixPath: toolsTopUrlKey,
  },
  'split-pdf': {
    icon: 'SplitPDF',
    title: 'pages:tools__index_page__constant_obj__split_a_pdf__title',
    description:
      'pages:tools__index_page__constant_obj__split_a_pdf__main_description',
    secondaryDescription:
      'pages:tools__index_page__constant_obj__split_a_pdf__secondary_description',
    urlKey: routerChildrenObject['split-pdf'],
    urlPrefixPath: toolsTopUrlKey,
  },
  'pdf-to-png': {
    icon: 'PDFToPNG',
    title: 'pages:tools__index_page__constant_obj__pdf_to_png__title',
    description:
      'pages:tools__index_page__constant_obj__pdf_to_png__main_description',
    secondaryDescription:
      'pages:tools__index_page__constant_obj__pdf_to_png__secondary_description',
    urlKey: routerChildrenObject['pdf-to-png'],
    urlPrefixPath: toolsTopUrlKey,
  },
  'pdf-to-jpeg': {
    icon: 'PDFToJPEG',
    title: 'pages:tools__index_page__constant_obj__pdf_to_jpeg__title',
    description:
      'pages:tools__index_page__constant_obj__pdf_to_jpeg__main_description',
    secondaryDescription:
      'pages:tools__index_page__constant_obj__pdf_to_jpeg__secondary_description',
    urlKey: routerChildrenObject['pdf-to-jpeg'],
    urlPrefixPath: toolsTopUrlKey,
  },
  'png-to-pdf': {
    icon: 'PNGToPDF',
    title: 'pages:tools__index_page__constant_obj__png_to_pdf__title',
    description:
      'pages:tools__index_page__constant_obj__png_to_pdf__main_description',
    secondaryDescription:
      'pages:tools__index_page__constant_obj__png_to_pdf__secondary_description',
    urlKey: routerChildrenObject['png-to-pdf'],
    urlPrefixPath: toolsTopUrlKey,
    accept: 'image/png',
  },
  'jpeg-to-pdf': {
    icon: 'JPEGToPDF',
    title: 'pages:tools__index_page__constant_obj__jpeg_to_pdf__title',
    description:
      'pages:tools__index_page__constant_obj__jpeg_to_pdf__main_description',
    secondaryDescription:
      'pages:tools__index_page__constant_obj__jpeg_to_pdf__secondary_description',
    urlKey: routerChildrenObject['jpeg-to-pdf'],
    urlPrefixPath: toolsTopUrlKey,
    accept: 'image/jpg,image/jpeg',
  },
  'heic-to-pdf': {
    icon: 'HEICToPDF',
    title: 'pages:tools__index_page__constant_obj__heic_to_pdf__title',
    description:
      'pages:tools__index_page__constant_obj__heic_to_pdf__main_description',
    secondaryDescription:
      'pages:tools__index_page__constant_obj__heic_to_pdf__secondary_description',
    urlKey: routerChildrenObject['heic-to-pdf'],
    urlPrefixPath: toolsTopUrlKey,
    accept: 'image/heic',
  },
  'pdf-to-html': {
    icon: 'PDFToHTML',
    title: 'pages:tools__index_page__constant_obj__pdf_to_html__title',
    description:
      'pages:tools__index_page__constant_obj__pdf_to_html__description',
    secondaryDescription:
      'pages:tools__index_page__constant_obj__pdf_to_html__description',
    urlKey: routerChildrenObject['pdf-to-html'],
    urlPrefixPath: toolsTopUrlKey,
  },
  'sign-pdf': {
    icon: 'SignPDF',
    title: 'pages:tools__index_page__constant_obj__sign_pdf__title',
    description:
      'pages:tools__index_page__constant_obj__sign_pdf__main_description',
    secondaryDescription:
      'pages:tools__index_page__constant_obj__sign_pdf__secondary_description',
    urlKey: routerChildrenObject['sign-pdf'],
    urlPrefixPath: toolsTopUrlKey,
  },
  'compress-pdf': {
    icon: 'CompressPDF',
    title: 'pages:tools__index_page__constant_obj__compress_pdf__title',
    description:
      'pages:tools__index_page__constant_obj__compress_pdf__main_description',
    secondaryDescription:
      'pages:tools__index_page__constant_obj__compress_pdf__main_description',
    urlKey: routerChildrenObject['compress-pdf'],
    urlPrefixPath: toolsTopUrlKey,
  },
  'ocr-pdf': {
    icon: 'OcrPDF',
    title: 'pages:tools__index_page__constant_obj__ocr_pdf__title',
    description:
      'pages:tools__index_page__constant_obj__ocr_pdf__main_description',
    secondaryDescription:
      'pages:tools__index_page__constant_obj__ocr_pdf__main_description',
    urlKey: routerChildrenObject['ocr-pdf'],
    urlPrefixPath: toolsTopUrlKey,
  },
  'rotate-pdf': {
    icon: 'RotatePDF',
    title: 'pages:tools__index_page__constant_obj__rotate_pdf__title',
    description:
      'pages:tools__index_page__constant_obj__rotate_pdf__main_description',
    secondaryDescription:
      'pages:tools__index_page__constant_obj__rotate_pdf__secondary_description',
    urlKey: routerChildrenObject['rotate-pdf'],
    urlPrefixPath: toolsTopUrlKey,
  },
  'number-pages': {
    icon: 'NumberPages',
    title: 'pages:tools__index_page__constant_obj__pdf_page_numbers__title',
    description:
      'pages:tools__index_page__constant_obj__pdf_page_numbers__main_description',
    secondaryDescription:
      'pages:tools__index_page__constant_obj__pdf_page_numbers__secondary_description',
    urlKey: routerChildrenObject['number-pages'],
    urlPrefixPath: toolsTopUrlKey,
  },
}

// 为了 i18n pdf-tools url，
// 提前声明好每个 pdf-tools 翻译过后的名字，用作 pathname
export const PDF_TOOLS_KEY_WITH_LOCALE: Record<
  IToolUrkKeyType,
  Record<I18nTypes, string>
> = {
  'pdf-to-png': {
    ar: 'تحويل-pdf-إلى-png',
    cs: 'pdf-na-png',
    da: 'pdf-til-png',
    de: 'pdf-zu-png',
    el: 'pdf-σε-png',
    en: 'pdf-to-png',
    es: 'pdf-a-png',
    fi: 'pdf-png',
    fil: 'pdf-to-png',
    fr: 'pdf-vers-png',
    he: 'pdf-ל-png',
    hi: 'pdf-से-png-में-बदलें',
    id: 'pdf-ke-png',
    it: 'pdf-in-png',
    ja: 'pdfからpngへ',
    ko: 'pdf를-png로-변환',
    ms: 'pdf-ke-png',
    nl: 'pdf-naar-png',
    no: 'pdf-til-png',
    pl: 'pdf-do-png',
    'pt-BR': 'pdf-para-png',
    'pt-PT': 'pdf-para-png',
    ro: 'pdf-în-png',
    ru: 'pdf-в-png',
    sv: 'pdf-till-png',
    th: 'pdf-เป็น-png',
    tr: "pdf'den-png'ye",
    ua: 'pdf-до-png',
    uk: 'pdf-سے-png',
    vi: 'pdf-sang-png',
    'zh-CN': 'pdf转png',
    'zh-TW': 'pdf-轉-png',
  },
  'pdf-to-jpeg': {
    ar: 'تحويل-pdf-إلى-jpeg',
    cs: 'pdf-na-jpeg',
    da: 'pdf-til-jpeg',
    de: 'pdf-zu-jpeg',
    el: 'pdf-σε-jpeg',
    en: 'pdf-to-jpeg',
    es: 'pdf-a-jpeg',
    fi: 'pdf-jpeg',
    fil: 'pdf-to-jpeg',
    fr: 'pdf-vers-jpeg',
    he: 'pdf-ל-jpeg',
    hi: 'pdf-से-jpeg-में-बदलें',
    id: 'pdf-ke-jpeg',
    it: 'pdf-in-jpeg',
    ja: 'pdfからjpegへ',
    ko: 'pdf를-jpeg로-변환',
    ms: 'pdf-ke-jpeg',
    nl: 'pdf-naar-jpeg',
    no: 'pdf-til-jpeg',
    pl: 'pdf-do-jpeg',
    'pt-BR': 'pdf-para-jpeg',
    'pt-PT': 'pdf-para-jpeg',
    ro: 'pdf-în-jpeg',
    ru: 'pdf-в-jpeg',
    sv: 'pdf-till-jpeg',
    th: 'pdf-เป็น-jpeg',
    tr: "pdf'den-jpeg'e",
    ua: 'pdf-до-jpeg',
    uk: 'pdf-سے-jpeg',
    vi: 'pdf-sang-jpeg',
    'zh-CN': 'pdf转jpeg',
    'zh-TW': 'pdf-轉-jpeg',
  },
  'merge-pdf': {
    ar: 'دمج-ملفات-pdf',
    cs: 'sloučit-pdf',
    da: 'flet-pdf',
    de: 'pdf-zusammenführen',
    el: 'συγχώνευση-pdf',
    en: 'merge-pdf',
    es: 'combinar-pdf',
    fi: 'yhdistä-pdf',
    fil: 'pagsamahin-ang-pdf',
    fr: 'fusionner-des-pdf',
    he: 'מיזוג-pdf',
    hi: 'पीडीएफ़-जोड़ें',
    id: 'gabungkan-pdf',
    it: 'unisci-pdf',
    ja: 'pdfの結合',
    ko: 'pdf-병합',
    ms: 'gabung-pdf',
    nl: 'pdf-samenvoegen',
    no: 'slå-sammen-pdf',
    pl: 'scal-pdf',
    'pt-BR': 'mesclar-pdf',
    'pt-PT': 'unir-pdfs',
    ro: 'unifică-pdf-uri',
    ru: 'объединить-pdf',
    sv: 'slå-samman-pdf',
    th: 'รวม-pdf',
    tr: 'pdf-birleştir',
    ua: "об'єднати-pdf",
    uk: 'pdf-کو-مرکب-کریں',
    vi: 'gộp-pdf',
    'zh-CN': '合并pdf',
    'zh-TW': '合併pdf',
  },
  'split-pdf': {
    ar: 'تقسيم-ملف-pdf',
    cs: 'rozdělit-pdf',
    da: 'opdel-en-pdf',
    de: 'pdf-teilen',
    el: 'διαίρεση-ενός-pdf',
    en: 'split-pdf',
    es: 'dividir-un-pdf',
    fi: 'jaa-pdf',
    fil: 'hatian-ang-pdf',
    fr: 'diviser-un-pdf',
    he: 'לחלק-pdf',
    hi: 'एक-पीडीएफ-विभाजित-करें',
    id: 'pisahkan-pdf',
    it: 'dividi-un-pdf',
    ja: 'pdfを分割する',
    ko: 'pdf-분할',
    ms: 'bahagikan-pdf',
    nl: 'pdf-splitsen',
    no: 'del-opp-en-pdf',
    pl: 'podziel-pdf',
    'pt-BR': 'dividir-um-pdf',
    'pt-PT': 'dividir-um-pdf',
    ro: 'divide-un-pdf',
    ru: 'разделить-pdf',
    sv: 'dela-upp-en-pdf',
    th: 'แยกไฟล์-pdf',
    tr: "pdf'yi-böl",
    ua: 'розділити-pdf',
    uk: 'pdf-کاٹیں',
    vi: 'chia-một-pdf',
    'zh-CN': '拆分pdf',
    'zh-TW': '分割-pdf',
  },
  'png-to-pdf': {
    ar: 'تحويل-png-إلى-pdf',
    cs: 'png-na-pdf',
    da: 'png-til-pdf',
    de: 'png-zu-pdf',
    el: 'png-σε-pdf',
    en: 'png-to-pdf',
    es: 'png-a-pdf',
    fi: 'png-pdf',
    fil: 'png-sa-pdf',
    fr: 'png-vers-pdf',
    he: 'png-ל-pdf',
    hi: 'png-से-pdf',
    id: 'png-ke-pdf',
    it: 'png-in-pdf',
    ja: 'pngからpdfへ',
    ko: 'png를-pdf로-변환',
    ms: 'png-ke-pdf',
    nl: 'png-naar-pdf',
    no: 'png-til-pdf',
    pl: 'png-do-pdf',
    'pt-BR': 'png-para-pdf',
    'pt-PT': 'png-para-pdf',
    ro: 'png-la-pdf',
    ru: 'png-в-pdf',
    sv: 'png-till-pdf',
    th: 'png-เป็น-pdf',
    tr: "png'den-pdf'e",
    ua: 'png-до-pdf',
    uk: 'png-سے-pdf',
    vi: 'chuyển-đổi-png-sang-pdf',
    'zh-CN': 'png转pdf',
    'zh-TW': 'png-轉-pdf',
  },
  'jpeg-to-pdf': {
    ar: 'تحويل-jpeg-إلى-pdf',
    cs: 'jpeg-na-pdf',
    da: 'jpeg-til-pdf',
    de: 'jpeg-zu-pdf',
    el: 'jpeg-σε-pdf',
    en: 'jpeg-to-pdf',
    es: 'jpeg-a-pdf',
    fi: 'jpeg-pdf',
    fil: 'jpeg-sa-pdf',
    fr: 'jpeg-vers-pdf',
    he: 'jpeg-ל-pdf',
    hi: 'jpeg-से-pdf',
    id: 'jpeg-ke-pdf',
    it: 'jpeg-in-pdf',
    ja: 'jpegからpdfへ',
    ko: 'jpeg를-pdf로-변환',
    ms: 'jpeg-ke-pdf',
    nl: 'jpeg-naar-pdf',
    no: 'jpeg-til-pdf',
    pl: 'jpeg-do-pdf',
    'pt-BR': 'jpeg-para-pdf',
    'pt-PT': 'jpeg-para-pdf',
    ro: 'jpeg-la-pdf',
    ru: 'jpeg-в-pdf',
    sv: 'jpeg-till-pdf',
    th: 'jpeg-เป็น-pdf',
    tr: "jpeg'ten-pdf'e",
    ua: 'jpeg-до-pdf',
    uk: 'jpeg-سے-pdf',
    vi: 'chuyển-đổi-jpeg-sang-pdf',
    'zh-CN': 'jpeg转pdf',
    'zh-TW': 'jpeg-轉-pdf',
  },
  'heic-to-pdf': {
    ar: 'تحويل-heic-إلى-pdf',
    cs: 'heic-na-pdf',
    da: 'heic-til-pdf',
    de: 'heic-zu-pdf',
    el: 'heic-σε-pdf',
    en: 'heic-to-pdf',
    es: 'heic-a-pdf',
    fi: 'heic-pdf',
    fil: 'heic-sa-pdf',
    fr: 'heic-vers-pdf',
    he: 'heic-ל-pdf',
    hi: 'heic-से-pdf-में-बदलें',
    id: 'heic-ke-pdf',
    it: 'heic-in-pdf',
    ja: 'heicからpdfへ',
    ko: 'heic를-pdf로-변환하기',
    ms: 'heic-ke-pdf',
    nl: 'heic-naar-pdf',
    no: 'heic-til-pdf',
    pl: 'heic-do-pdf',
    'pt-BR': 'heic-para-pdf',
    'pt-PT': 'heic-para-pdf',
    ro: 'heic-la-pdf',
    ru: 'heic-в-pdf',
    sv: 'heic-till-pdf',
    th: 'heic-เป็น-pdf',
    tr: "heic'ten-pdf'e",
    ua: 'heic-до-pdf',
    uk: 'heic-سے-pdf',
    vi: 'heic-thành-pdf',
    'zh-CN': 'heic转pdf',
    'zh-TW': 'heic-轉-pdf',
  },
  'pdf-to-html': {
    ar: 'تحويل-pdf-إلى-html',
    cs: 'pdf-na-html',
    da: 'pdf-til-html',
    de: 'pdf-zu-html',
    el: 'pdf-σε-html',
    en: 'pdf-to-html',
    es: 'pdf-a-html',
    fi: 'pdf-html:ksi',
    fil: 'pdf-sa-html',
    fr: 'pdf-vers-html',
    he: 'pdf-ל-html',
    hi: 'pdf-से-html-में-रूपांतरण',
    id: 'pdf-ke-html',
    it: 'pdf-in-html',
    ja: 'pdfをhtmlに変換する',
    ko: 'pdf를-html로-변환',
    ms: 'pdf-ke-html',
    nl: 'pdf-naar-html',
    no: 'pdf-til-html',
    pl: 'pdf-do-html',
    'pt-BR': 'pdf-para-html',
    'pt-PT': 'pdf-para-html',
    ro: 'pdf-în-html',
    ru: 'pdf-в-html',
    sv: 'pdf-till-html',
    th: 'pdf-เป็น-html',
    tr: "pdf'yi-html'e-dönüştür",
    ua: 'pdf-в-html',
    uk: 'pdf-سے-html-تک',
    vi: 'chuyển-đổi-pdf-thành-html',
    'zh-CN': 'pdf转html',
    'zh-TW': 'pdf轉html',
  },
  'sign-pdf': {
    ar: 'وقع-على-ملف-pdf',
    cs: 'podepsat-pdf',
    da: 'underskriv-pdf',
    de: 'pdf-unterschreiben',
    el: 'υπογράψτε-pdf',
    en: 'sign-pdf',
    es: 'firmar-pdf',
    fi: 'allekirjoita-pdf',
    fil: 'lagdaan-ang-pdf',
    fr: 'signer-un-pdf',
    he: 'חתום-על-pdf',
    hi: 'पीडीएफ-पर-हस्ताक्षर-करें',
    id: 'tanda-tangan-pdf',
    it: 'firma-pdf',
    ja: 'pdfに署名する',
    ko: 'pdf에-서명하기',
    ms: 'tandatangan-pdf',
    nl: 'pdf-ondertekenen',
    no: 'signer-pdf',
    pl: 'podpisz-pdf',
    'pt-BR': 'assinar-pdf',
    'pt-PT': 'assinar-pdf',
    ro: 'semnează-pdf',
    ru: 'подписать-pdf',
    sv: 'signera-pdf',
    th: 'เซ็นต์-pdf',
    tr: 'pdf-i̇mzala',
    ua: 'підписати-pdf',
    uk: 'pdf-پر-دستخط-کریں',
    vi: 'ký-pdf',
    'zh-CN': '签署pdf',
    'zh-TW': '簽署pdf',
  },
  'compress-pdf': {
    ar: 'ضغط-pdf',
    cs: 'zmenšit-pdf',
    da: 'komprimer-pdf',
    de: 'pdf-komprimieren',
    el: 'συμπίεση-pdf',
    en: 'compress-pdf',
    es: 'comprimir-pdf',
    fi: 'pakkaa-pdf',
    fil: 'pisilin-ang-pdf',
    fr: 'compresser-pdf',
    he: 'דחיסת-pdf',
    hi: 'पीडीएफ-को-संकुचित-करें',
    id: 'kompres-pdf',
    it: 'comprimi-pdf',
    ja: 'pdfを圧縮する',
    ko: 'pdf-압축',
    ms: 'kompres-pdf',
    nl: 'pdf-comprimeren',
    no: 'komprimer-pdf',
    pl: 'skompresuj-pdf',
    'pt-BR': 'comprimir-pdf',
    'pt-PT': 'comprimir-pdf',
    ro: 'comprimare-pdf',
    ru: 'сжатие-pdf',
    sv: 'komprimera-pdf',
    th: 'บีบอัด-pdf',
    tr: 'pdf-sıkıştır',
    ua: 'стиснути-pdf',
    uk: 'pdf-کمپریس-کریں',
    vi: 'nén-pdf',
    'zh-CN': '压缩pdf',
    'zh-TW': '壓縮pdf',
  },
  'ocr-pdf': {
    ar: 'تحويل-pdf-إلى-نص',
    cs: 'ocr-pdf',
    da: 'ocr-pdf',
    de: 'ocr-pdf',
    el: 'ocr-pdf',
    en: 'ocr-pdf',
    es: 'ocr-de-pdf',
    fi: 'ocr-pdf',
    fil: 'ocr-pdf',
    fr: 'ocr-pdf',
    he: 'ocr-pdf',
    hi: 'ocr-पीडीएफ',
    id: 'ocr-pdf',
    it: 'ocr-pdf',
    ja: 'ocr-pdf',
    ko: 'ocr-pdf',
    ms: 'ocr-pdf',
    nl: 'ocr-pdf',
    no: 'ocr-pdf',
    pl: 'ocr-pdf',
    'pt-BR': 'ocr-de-pdf',
    'pt-PT': 'ocr-de-pdf',
    ro: 'ocr-pdf',
    ru: 'ocr-pdf',
    sv: 'ocr-pdf',
    th: 'ocr-pdf',
    tr: 'ocr-pdf',
    ua: 'ocr-pdf',
    uk: 'ocr-pdf',
    vi: 'ocr-pdf',
    'zh-CN': 'ocr-pdf',
    'zh-TW': 'ocr-pdf',
  },
  'number-pages': {
    ar: 'أرقام-الصفحات',
    cs: 'číslování-stránek',
    da: 'siderummer',
    de: 'seiten-nummerieren',
    el: 'αρίθμηση-σελίδων',
    en: 'number-pages',
    es: 'numerar-páginas',
    fi: 'sivunumerot',
    fil: 'magdagdag-ng-mga-pahina',
    fr: 'numéroter-les-pages',
    he: 'מספר-עמודים',
    hi: 'पृष्ठ-संख्या',
    id: 'nomor-halaman',
    it: 'numerazione-pagine',
    ja: 'ページ番号',
    ko: '페이지-번호',
    ms: 'nombor-halaman',
    nl: 'paginanummers',
    no: 'sidenummerering',
    pl: 'numeruj-strony',
    'pt-BR': 'número-de-páginas',
    'pt-PT': 'número-de-páginas',
    ro: 'număr-pagini',
    ru: 'номера-страниц',
    sv: 'sidorummer',
    th: 'หมายเลขหน้า',
    tr: 'sayfa-numaraları',
    ua: 'номери-сторінок',
    uk: 'صفحات-کی-تعداد',
    vi: 'số-trang',
    'zh-CN': '排页数',
    'zh-TW': '排頁數',
  },
  'rotate-pdf': {
    ar: 'تدوير-ملف-pdf',
    cs: 'otočit-pdf',
    da: 'roter-pdf',
    de: 'pdf-drehen',
    el: 'περιστροφή-pdf',
    en: 'rotate-pdf',
    es: 'rotar-pdf',
    fi: 'käännä-pdf',
    fil: 'i-rotate-ang-pdf',
    fr: 'faire-pivoter-le-pdf',
    he: 'הטיה-של-pdf',
    hi: 'पीडीएफ-घुमाएं',
    id: 'putar-pdf',
    it: 'ruota-pdf',
    ja: 'pdfを回転',
    ko: 'pdf-회전',
    ms: 'putar-pdf',
    nl: 'pdf-roteren',
    no: 'roter-pdf',
    pl: 'obróć-pdf',
    'pt-BR': 'girar-pdf',
    'pt-PT': 'rodar-pdf',
    ro: 'rotire-pdf',
    ru: 'повернуть-pdf',
    sv: 'rotera-pdf',
    th: 'หมุน-pdf',
    tr: 'pdf-döndür',
    ua: 'повернути-pdf',
    uk: 'pdf-گھمائیں',
    vi: 'xoay-pdf',
    'zh-CN': '旋转pdf',
    'zh-TW': '旋轉pdf',
  },
}
