import { Box, Typography } from '@mui/material';
import React, { FC } from 'react';

import AppContainer from '@/app_layout/AppContainer';
import AppDefaultSeoLayout from '@/app_layout/AppDefaultSeoLayout';
import ProLink from '@/components/ProLink';

const PrivacyPage: FC = () => {
  // const { customTheme } = useCustomTheme();

  return (
    <AppContainer sx={{ wordBreak: 'break-word', py: 4 }}>
      <AppDefaultSeoLayout
        description={'Read the MaxAI.me privacy policy.'}
        title={'Privacy Policy | MaxAI.me'}
      />
      <Box>
        <Typography variant='h1' component={'h1'} gutterBottom sx={{ mb: 2 }}>
          Privacy Policy
        </Typography>
        <Typography variant='body2' gutterBottom sx={{ mb: 2 }}>
          Last Updated: June 29, 2023
        </Typography>
        <Typography variant='body2' gutterBottom sx={{ mb: 2 }}>
          {`Welcome to the Privacy Policy for the MaxAI.me Chrome extension
          (hereinafter referred to as "MaxAI", "MaxAI.me", "we", "us",
          or "our"). We understand the importance of your privacy, and we are
          committed to protecting your personal information. This Privacy Policy
          outlines the types of information we collect, how we use it, and the
          measures we take to protect your data.`}
        </Typography>
        <Typography variant='body2' gutterBottom>
          {`By using the MaxAI Chrome extension, you acknowledge and agree to the terms and conditions of this Privacy Policy. If you do not agree with any part of this Privacy Policy, please do not use or install the MaxAI Chrome extension.`}
        </Typography>
      </Box>
      <Box sx={{ mt: 4 }}>
        <Typography variant='h2' component={'h2'} gutterBottom sx={{ mb: 2 }}>
          Information We Do Not Collect
        </Typography>
        <Typography variant='h3' gutterBottom sx={{ mb: 2 }}>
          Personal Information
        </Typography>
        <Typography variant='body2' gutterBottom sx={{ mb: 2 }}>
          We take your privacy seriously and only collect your email and name to
          identify you when you log in, helping to sync your settings across
          different browsers and devices. Other than that, we do not collect any
          other personal information. The MaxAI Chrome extension operates
          without requiring any additional personal data from you, and we do not
          store such information.
        </Typography>
      </Box>
      <Box sx={{ mt: 4 }}>
        <Typography variant='h2' component={'h2'} gutterBottom sx={{ mb: 2 }}>
          Information We Collect
        </Typography>
        <Typography variant='h3' gutterBottom sx={{ mb: 2 }}>
          Chrome Extension Automatically Generated Reports
        </Typography>
        <Typography variant='body2' gutterBottom sx={{ mb: 2 }}>
          One of the types of information we collect from users is the Chrome
          extension automatically generated report. This information is used for
          the sole purpose of improving the functionality of the MaxAI Chrome
          extension and understanding the usage patterns of our users. The
          collected data may include technical information such as browser
          version, extension version, and operating system.
        </Typography>
        {/* <Typography variant='h3' gutterBottom sx={{ mb: 2 }}>
          Google Analytics
        </Typography>
        <Typography variant='body2' gutterBottom sx={{ mb: 2 }}>
          {`The second type of information we collect is default information about
          user interactions with the MaxAI Chrome extension through the use
          of Google Analytics, a web analytics service provided by Google Inc.
          ("Google"). Google Analytics uses cookies to help us analyze how users
          use the extension. The information generated by the cookies about your
          use of the extension (including your IP address) will be transmitted
          to and stored by Google on servers in the United States.`}
        </Typography> */}
      </Box>
      <Box sx={{ mt: 4 }}>
        <Typography variant='h2' component={'h2'} gutterBottom sx={{ mb: 2 }}>
          How we use your information
        </Typography>
        <Typography variant='body2' gutterBottom sx={{ mb: 2 }}>
          We use the information we collect, including Chrome extension
          automatically generated reports, to:
        </Typography>
        <Typography variant='body2' gutterBottom sx={{ mb: 2 }}>
          1) {`Improve the MaxAI Chrome extension's functionality.`}
        </Typography>
        <Typography variant='body2' gutterBottom sx={{ mb: 2 }}>
          2) Analyze usage patterns to better understand user preferences.
        </Typography>
        <Typography variant='body2' gutterBottom sx={{ mb: 2 }}>
          3) Identify and troubleshoot issues with the Chrome extension.
        </Typography>
        <Typography variant='body2' gutterBottom sx={{ mb: 2 }}>
          4) Improve the overall user experience.
        </Typography>
      </Box>
      <Box sx={{ mt: 4 }}>
        <Typography variant='h2' component={'h2'} gutterBottom sx={{ mb: 2 }}>
          Information Security
        </Typography>
        <Typography variant='body2' gutterBottom sx={{ mb: 2 }}>
          We take appropriate measures to protect the limited information we
          collect from unauthorized access, disclosure, alteration, or
          destruction. We follow industry-standard practices to ensure the
          security of the data we manage.
        </Typography>
      </Box>
      <Box sx={{ mt: 4 }}>
        <Typography variant='h2' component={'h2'} gutterBottom sx={{ mb: 2 }}>
          Marketing and advertising
        </Typography>
        <Typography variant='body2' gutterBottom sx={{ mb: 2 }}>
          Where required by law we will only send you marketing information,
          including sending you updates and information about our new products
          and services, upcoming events or other promotions or news, including
          by email or push notification, as permitted by law. You may opt-out of
          receiving such emails by following the instructions in each
          promotional email we send you or by updating your user settings. In
          addition, if at any time you wish not to receive future communications
          or you wish to have your name deleted from our mailing lists, please
          contact us at{' '}
          <ProLink href={'mailto:hello@maxai.me'}>hello@maxai.me</ProLink>. We
          will continue to contact you via email regarding the provision of our
          Services and to respond to your requests.
        </Typography>
      </Box>
      <Box sx={{ mt: 4 }}>
        <Typography variant='h2' component={'h2'} gutterBottom sx={{ mb: 2 }}>
          Changes to the Privacy Policy
        </Typography>
        <Typography variant='body2' gutterBottom sx={{ mb: 2 }}>
          {`We may update our Privacy Policy from time to time. Any changes to
          this Privacy Policy will be posted on this page, and the "Last
          Updated" date at the top will be revised accordingly. Your continued
          use of the MaxAI Chrome extension after any changes to the
          Privacy Policy constitutes your acceptance of the updated policy.`}
        </Typography>
      </Box>
      <Box sx={{ mt: 4 }}>
        <Typography variant='h2' component={'h2'} gutterBottom sx={{ mb: 2 }}>
          Contact Us
        </Typography>
        <Typography variant='body2' gutterBottom sx={{ mb: 2 }}>
          If you have any questions or concerns about our Privacy Policy, please
          feel free to contact us at{' '}
          <ProLink href={'mailto:hello@maxai.me'}>hello@maxai.me</ProLink>
        </Typography>
      </Box>
    </AppContainer>
  );
};

export default PrivacyPage;
