export const COUNTRIES_MAP: Map<string, string> = new Map(
  Object.entries({
    Andorra: 'ad',
    'United Arab Emirates': 'ae',
    Afghanistan: 'af',
    'Antigua and Barbuda': 'ag',
    Anguilla: 'ai',
    Albania: 'al',
    Armenia: 'am',
    Angola: 'ao',
    Antarctica: 'aq',
    Argentina: 'ar',
    'American Samoa': 'as',
    Austria: 'at',
    Australia: 'au',
    Aruba: 'aw',
    'Åland Islands': 'ax',
    Azerbaijan: 'az',
    'Bosnia and Herzegovina': 'ba',
    Barbados: 'bb',
    Bangladesh: 'bd',
    Belgium: 'be',
    'Burkina Faso': 'bf',
    Bulgaria: 'bg',
    Bahrain: 'bh',
    Burundi: 'bi',
    Benin: 'bj',
    'Saint Barthélemy': 'bl',
    Bermuda: 'bm',
    Brunei: 'bn',
    Bolivia: 'bo',
    'Bolivia, Plurinational State of': 'bo',
    'Caribbean Netherlands': 'bq',
    Brazil: 'br',
    Bahamas: 'bs',
    Bhutan: 'bt',
    'Bouvet Island': 'bv',
    Botswana: 'bw',
    Belarus: 'by',
    Belize: 'bz',
    Canada: 'ca',
    'Cocos (Keeling) Islands': 'cc',
    'DR Congo': 'cd',
    'Congo, the Democratic Republic of the': 'cd',
    'Democratic Republic of the Congo': 'cd',
    'Central African Republic': 'cf',
    'Republic of the Congo': 'cg',
    Switzerland: 'ch',
    "Côte d'Ivoire (Ivory Coast)": 'ci',
    'Cook Islands': 'ck',
    Chile: 'cl',
    Cameroon: 'cm',
    China: 'cn',
    Colombia: 'co',
    'Costa Rica': 'cr',
    Cuba: 'cu',
    'Cape Verde': 'cv',
    Curaçao: 'cw',
    'Christmas Island': 'cx',
    Cyprus: 'cy',
    Czechia: 'cz',
    'Czech Republic': 'cz',
    Germany: 'de',
    Djibouti: 'dj',
    Denmark: 'dk',
    Dominica: 'dm',
    'Dominican Republic': 'do',
    Algeria: 'dz',
    Ecuador: 'ec',
    Estonia: 'ee',
    Egypt: 'eg',
    'Western Sahara': 'eh',
    Eritrea: 'er',
    Spain: 'es',
    Ethiopia: 'et',
    'European Union': 'eu',
    Finland: 'fi',
    Fiji: 'fj',
    'Falkland Islands': 'fk',
    Micronesia: 'fm',
    'Faroe Islands': 'fo',
    France: 'fr',
    Gabon: 'ga',
    'United Kingdom': 'gb',
    England: 'gb-eng',
    'Northern Ireland': 'gb-nir',
    Scotland: 'gb-sct',
    Wales: 'gb-wls',
    Grenada: 'gd',
    Georgia: 'us-ga',
    'French Guiana': 'gf',
    Guernsey: 'gg',
    Ghana: 'gh',
    Gibraltar: 'gi',
    Greenland: 'gl',
    Gambia: 'gm',
    Guinea: 'gn',
    Guadeloupe: 'gp',
    'Equatorial Guinea': 'gq',
    Greece: 'gr',
    'South Georgia': 'gs',
    Guatemala: 'gt',
    Guam: 'gu',
    'Guinea-Bissau': 'gw',
    Guyana: 'gy',
    'Hong Kong': 'hk',
    'Heard Island and McDonald Islands': 'hm',
    Honduras: 'hn',
    Croatia: 'hr',
    Haiti: 'ht',
    Hungary: 'hu',
    Indonesia: 'id',
    Ireland: 'ie',
    Israel: 'il',
    'Isle of Man': 'im',
    India: 'in',
    'British Indian Ocean Territory': 'io',
    Iraq: 'iq',
    Iran: 'ir',
    Iceland: 'is',
    Italy: 'it',
    Jersey: 'je',
    Jamaica: 'jm',
    Jordan: 'jo',
    Japan: 'jp',
    Kenya: 'ke',
    Kyrgyzstan: 'kg',
    Cambodia: 'kh',
    Kiribati: 'ki',
    Comoros: 'km',
    'Saint Kitts and Nevis': 'kn',
    'North Korea': 'kp',
    'South Korea': 'kr',
    'Korea, Republic of': 'kr',
    Kuwait: 'kw',
    'Cayman Islands': 'ky',
    Kazakhstan: 'kz',
    Laos: 'la',
    Lebanon: 'lb',
    'Saint Lucia': 'lc',
    Liechtenstein: 'li',
    'Sri Lanka': 'lk',
    Liberia: 'lr',
    Lesotho: 'ls',
    Lithuania: 'lt',
    Luxembourg: 'lu',
    Latvia: 'lv',
    Libya: 'ly',
    Morocco: 'ma',
    Monaco: 'mc',
    Moldova: 'md',
    'Moldova, Republic of': 'md',
    Montenegro: 'me',
    'Saint Martin': 'mf',
    Madagascar: 'mg',
    'Marshall Islands': 'mh',
    'North Macedonia': 'mk',
    Mali: 'ml',
    Myanmar: 'mm',
    Mongolia: 'mn',
    Macau: 'mo',
    'Northern Mariana Islands': 'mp',
    Martinique: 'mq',
    Mauritania: 'mr',
    Montserrat: 'ms',
    Malta: 'mt',
    Mauritius: 'mu',
    Maldives: 'mv',
    Malawi: 'mw',
    Mexico: 'mx',
    Malaysia: 'my',
    Mozambique: 'mz',
    Namibia: 'na',
    'New Caledonia': 'nc',
    Niger: 'ne',
    'Norfolk Island': 'nf',
    Nigeria: 'ng',
    Nicaragua: 'ni',
    Netherlands: 'nl',
    Norway: 'no',
    Nepal: 'np',
    Nauru: 'nr',
    Niue: 'nu',
    'New Zealand': 'nz',
    Oman: 'om',
    Panama: 'pa',
    Peru: 'pe',
    'French Polynesia': 'pf',
    'Papua New Guinea': 'pg',
    Philippines: 'ph',
    Pakistan: 'pk',
    Poland: 'pl',
    'Saint Pierre and Miquelon': 'pm',
    'Pitcairn Islands': 'pn',
    'Puerto Rico': 'pr',
    Palestine: 'ps',
    Portugal: 'pt',
    Palau: 'pw',
    Paraguay: 'py',
    Qatar: 'qa',
    Réunion: 're',
    Romania: 'ro',
    Serbia: 'rs',
    Russia: 'ru',
    'Russian Federation': 'ru',
    Rwanda: 'rw',
    'Saudi Arabia': 'sa',
    'Solomon Islands': 'sb',
    Seychelles: 'sc',
    Sudan: 'sd',
    Sweden: 'se',
    Singapore: 'sg',
    'Saint Helena, Ascension and Tristan da Cunha': 'sh',
    Slovenia: 'si',
    'Svalbard and Jan Mayen': 'sj',
    Slovakia: 'sk',
    'Sierra Leone': 'sl',
    'San Marino': 'sm',
    Senegal: 'sn',
    Somalia: 'so',
    Suriname: 'sr',
    'South Sudan': 'ss',
    'São Tomé and Príncipe': 'st',
    'El Salvador': 'sv',
    'Sint Maarten': 'sx',
    Syria: 'sy',
    'Eswatini (Swaziland)': 'sz',
    'Turks and Caicos Islands': 'tc',
    Chad: 'td',
    'French Southern and Antarctic Lands': 'tf',
    Togo: 'tg',
    Thailand: 'th',
    Tajikistan: 'tj',
    Tokelau: 'tk',
    'Timor-Leste': 'tl',
    Turkmenistan: 'tm',
    Tunisia: 'tn',
    Tonga: 'to',
    Turkey: 'tr',
    'Trinidad and Tobago': 'tt',
    Tuvalu: 'tv',
    Taiwan: 'cn',
    'Taiwan, Province of China': 'cn',
    Tanzania: 'tz',
    Ukraine: 'ua',
    Uganda: 'ug',
    'United States Minor Outlying Islands': 'um',
    'United Nations': 'un',
    'United States': 'us',
    Alaska: 'us-ak',
    Alabama: 'us-al',
    Arkansas: 'us-ar',
    Arizona: 'us-az',
    California: 'us-ca',
    Colorado: 'us-co',
    Connecticut: 'us-ct',
    Delaware: 'us-de',
    Florida: 'us-fl',
    Hawaii: 'us-hi',
    Iowa: 'us-ia',
    Idaho: 'us-id',
    Illinois: 'us-il',
    Indiana: 'us-in',
    Kansas: 'us-ks',
    Kentucky: 'us-ky',
    Louisiana: 'us-la',
    Massachusetts: 'us-ma',
    Maryland: 'us-md',
    Maine: 'us-me',
    Michigan: 'us-mi',
    Minnesota: 'us-mn',
    Missouri: 'us-mo',
    Mississippi: 'us-ms',
    Montana: 'us-mt',
    'North Carolina': 'us-nc',
    'North Dakota': 'us-nd',
    Nebraska: 'us-ne',
    'New Hampshire': 'us-nh',
    'New Jersey': 'us-nj',
    'New Mexico': 'us-nm',
    Nevada: 'us-nv',
    'New York': 'us-ny',
    Ohio: 'us-oh',
    Oklahoma: 'us-ok',
    Oregon: 'us-or',
    Pennsylvania: 'us-pa',
    'Rhode Island': 'us-ri',
    'South Carolina': 'us-sc',
    'South Dakota': 'us-sd',
    Tennessee: 'us-tn',
    Texas: 'us-tx',
    Utah: 'us-ut',
    Virginia: 'us-va',
    Vermont: 'us-vt',
    Washington: 'us-wa',
    Wisconsin: 'us-wi',
    'West Virginia': 'us-wv',
    Wyoming: 'us-wy',
    Uruguay: 'uy',
    Uzbekistan: 'uz',
    'Vatican City (Holy See)': 'va',
    'Saint Vincent and the Grenadines': 'vc',
    Venezuela: 've',
    'Venezuela, Bolivarian Republic of': 've',
    'British Virgin Islands': 'vg',
    'United States Virgin Islands': 'vi',
    Vietnam: 'vn',
    'Viet Nam': 'vn',
    Vanuatu: 'vu',
    'Wallis and Futuna': 'wf',
    Samoa: 'ws',
    Kosovo: 'xk',
    Yemen: 'ye',
    Mayotte: 'yt',
    'South Africa': 'za',
    Zambia: 'zm',
    Zimbabwe: 'zw',
  }),
);

export const TechnologySort = [
  'Ecommerce',
  'Shopify apps',
  'Shopify themes',
  'WordPress themes',
  'Drupal themes',
  'Analytics',
  'Advertising',
  'Retargeting',
  'Affiliate programs',
  'Referral marketing',
  'Email',
  'Webmail',
  'Marketing automation',
  'Widgets',
  'SEO',
  'Blogs',
  'CMS',
  'Payment processors',
  'Buy now pay later',
  'Reviews',
  'Personalisation',
  'Search engines',
  'Cross border ecommerce',
  'Page builders',
  'User onboarding',
  'Cart abandonment',
  'Shipping carriers',
  'Returns',
  'Livestreaming',
  'Ticket booking',
  'Comment systems',
  'Loyalty & rewards',
  'CRM',
  'Live chat',
  'Documentation',
  'Issue trackers',
  'RUM',
  'A/B Testing',
  'Tag managers',
  'Customer data platform',
  'JavaScript libraries',
  'JavaScript frameworks',
  'JavaScript graphics',
  'Web frameworks',
  'Web server extensions',
  'Mobile frameworks',
  'CDN',
  'Development',
  'Authentication',
  'Video players',
  'UI frameworks',
  'Caching',
  'Reverse proxies',
  'Load balancers',
  'Web servers',
  'Hosting',
  'PaaS',
  'IaaS',
  'Security',
  'Cookie compliance',
  'Font scripts',
  'Performance',
  'Message boards',
  'Photo galleries',
  'Wikis',
  'LMS',
  'Media servers',
  'Remote access',
  'Feed readers',
  'DMS',
  'Accounting',
  'Static site generator',
  'Database managers',
  'Hosting panels',
  'Network devices',
  'Control systems',
  'Network storage',
  'CI',
  'Editors',
  'Rich text editors',
  'Programming languages',
  'Databases',
  'Cryptominers',
  'Operating systems',
  'Maps',
  'Containers',
  'Webcams',
  'Accessibility',
  'SSL/TLS certificate authorities',
  'Appointment scheduling',
  'Surveys',
  'Geolocation',
  'Browser fingerprinting',
  'Feature management',
  'Segmentation',
  'WordPress plugins',
  'Translation',
  'Reservations & delivery',
  'Digital asset management',
  'Content curation',
  'Recruitment & staffing',
  'Miscellaneous',
];

export const CURRENCIES: { [key: string]: string } = {
  '1inch': '1inch Network',
  aave: 'Aave',
  ada: 'Cardano',
  aed: 'United Arab Emirates Dirham',
  afn: 'Afghan afghani',
  algo: 'Algorand',
  all: 'Albanian lek',
  amd: 'Armenian dram',
  amp: 'Synereo',
  ang: 'Netherlands Antillean Guilder',
  aoa: 'Angolan kwanza',
  ar: 'Arweave',
  ars: 'Argentine peso',
  atom: 'Atomic Coin',
  aud: 'Australian dollar',
  avax: 'Avalanche',
  awg: 'Aruban florin',
  axs: 'AXS',
  azn: 'Azerbaijani manat',
  bam: 'Bosnia-Herzegovina Convertible Mark',
  bat: 'Basic Attention Token',
  bbd: 'Bajan dollar',
  bch: 'Bitcoin Cash',
  bdt: 'Bangladeshi taka',
  bgn: 'Bulgarian lev',
  bhd: 'Bahraini dinar',
  bif: 'Burundian Franc',
  bmd: 'Bermudan dollar',
  bnb: 'Binance Coin',
  bnd: 'Brunei dollar',
  bob: 'Bolivian boliviano',
  brl: 'Brazilian real',
  bsd: 'Bahamian dollar',
  bsv: 'Bitcoin SV',
  btc: 'Bitcoin',
  btcb: 'Bitcoin BEP2',
  btg: 'Bitcoin Gold',
  btn: 'Bhutan currency',
  busd: 'Binance USD',
  bwp: 'Botswanan Pula',
  byn: 'New Belarusian Ruble',
  byr: 'Belarusian Ruble',
  bzd: 'Belize dollar',
  cad: 'Canadian dollar',
  cake: 'PancakeSwap',
  cdf: 'Congolese franc',
  celo: 'Celo',
  chf: 'Swiss franc',
  chz: 'Chiliz',
  clf: 'Chilean Unit of Account (UF)',
  clp: 'Chilean peso',
  cny: 'Chinese Yuan',
  comp: 'Compound Coin',
  cop: 'Colombian peso',
  crc: 'Costa Rican Colón',
  cro: 'Crypto.com Chain Token',
  crv: 'Cravy',
  cuc: 'Cuban peso',
  cup: 'Cuban Peso',
  cve: 'Cape Verdean escudo',
  cvx: 'Convex Finance',
  czk: 'Czech koruna',
  dai: 'Dai',
  dash: 'Dash',
  dcr: 'Decred',
  dfi: 'DfiStarter',
  djf: 'Djiboutian franc',
  dkk: 'Danish krone',
  doge: 'Dogecoin',
  dop: 'Dominican peso',
  dot: 'Dotcoin',
  dzd: 'Algerian dinar',
  egld: 'Elrond',
  egp: 'Egyptian pound',
  enj: 'Enjin Coin',
  eos: 'EOS',
  ern: 'Eritrean nakfa',
  etb: 'Ethiopian birr',
  etc: 'Ethereum Classic',
  eth: 'Ether',
  eur: 'Euro',
  fei: 'Fei USD',
  fil: 'FileCoin',
  fjd: 'Fijian dollar',
  fkp: 'Falkland Islands pound',
  flow: 'Flow',
  frax: 'Frax',
  ftm: 'Fantom',
  ftt: 'FarmaTrust',
  gala: 'Gala',
  gbp: 'Pound sterling',
  gel: 'Georgian lari',
  ggp: 'GGPro',
  ghs: 'Ghanaian cedi',
  gip: 'Gibraltar pound',
  gmd: 'Gambian dalasi',
  gnf: 'Guinean franc',
  gno: 'Gnosis',
  grt: 'Golden Ratio Token',
  gt: 'GateToken',
  gtq: 'Guatemalan quetzal',
  gyd: 'Guyanaese Dollar',
  hbar: 'Hedera',
  hkd: 'Hong Kong dollar',
  hnl: 'Honduran lempira',
  hnt: 'Helium',
  hot: 'Hydro Protocol',
  hrk: 'Croatian kuna',
  ht: 'Huobi Token',
  htg: 'Haitian gourde',
  huf: 'Hungarian forint',
  icp: 'Internet Computer',
  idr: 'Indonesian rupiah',
  ils: 'Israeli New Shekel',
  imp: 'CoinIMP',
  inj: 'Injective',
  inr: 'Indian rupee',
  iqd: 'Iraqi dinar',
  irr: 'Iranian rial',
  isk: 'Icelandic króna',
  jep: 'Jersey Pound',
  jmd: 'Jamaican dollar',
  jod: 'Jordanian dinar',
  jpy: 'Japanese yen',
  kava: 'Kava',
  kcs: 'Kucoin',
  kda: 'Kadena',
  kes: 'Kenyan shilling',
  kgs: 'Kyrgystani Som',
  khr: 'Cambodian riel',
  klay: 'Klaytn',
  kmf: 'Comorian franc',
  knc: 'Kyber Network',
  kpw: 'North Korean won',
  krw: 'South Korean won',
  ksm: 'Kusama',
  kwd: 'Kuwaiti dinar',
  kyd: 'Cayman Islands dollar',
  kzt: 'Kazakhstani tenge',
  lak: 'Laotian Kip',
  lbp: 'Lebanese pound',
  leo: 'LEOcoin',
  link: 'ChainLink',
  lkr: 'Sri Lankan rupee',
  lrc: 'Loopring',
  lrd: 'Liberian dollar',
  lsl: 'Lesotho loti',
  ltc: 'Litecoin',
  ltl: 'Lithuanian litas',
  luna: 'Luna Coin',
  lvl: 'Latvian lats',
  lyd: 'Libyan dinar',
  mad: 'Moroccan dirham',
  mana: 'Decentraland',
  matic: 'Polygon',
  mdl: 'Moldovan leu',
  mga: 'Malagasy ariary',
  mina: 'Mina',
  miota: 'IOTA',
  mkd: 'Macedonian denar',
  mkr: 'Maker',
  mmk: 'Myanmar Kyat',
  mnt: 'Mongolian tugrik',
  mop: 'Macanese pataca',
  mro: 'Mauritanian ouguiya',
  mur: 'Mauritian rupee',
  mvr: 'Maldivian rufiyaa',
  mwk: 'Malawian kwacha',
  mxn: 'Mexican peso',
  myr: 'Malaysian ringgit',
  mzn: 'Mozambican Metical',
  nad: 'Namibian dollar',
  near: 'NEAR Protocol',
  neo: 'NEO',
  nexo: 'NEXO',
  ngn: 'Nigerian naira',
  nio: 'Nicaraguan córdoba',
  nok: 'Norwegian krone',
  npr: 'Nepalese rupee',
  nzd: 'New Zealand dollar',
  okb: 'Okex',
  omr: 'Omani rial',
  one: 'Menlo One',
  pab: 'Panamanian balboa',
  paxg: 'PAX Gold',
  pen: 'Sol',
  pgk: 'Papua New Guinean kina',
  php: 'Philippine peso',
  pkr: 'Pakistani rupee',
  pln: 'Poland złoty',
  pyg: 'Paraguayan guarani',
  qar: 'Qatari Rial',
  qnt: 'Quant',
  qtum: 'QTUM',
  ron: 'Romanian leu',
  rsd: 'Serbian dinar',
  rub: 'Russian ruble',
  rune: 'THORChain (ERC20)',
  rwf: 'Rwandan Franc',
  sand: 'BeachCoin',
  sar: 'Saudi riyal',
  sbd: 'Solomon Islands dollar',
  scr: 'Seychellois rupee',
  sdg: 'Sudanese pound',
  sek: 'Swedish krona',
  sgd: 'Singapore dollar',
  shib: 'Shiba Inu',
  shp: 'Saint Helena pound',
  sll: 'Sierra Leonean leone',
  sol: 'Sola',
  sos: 'Somali shilling',
  srd: 'Surinamese dollar',
  std: 'São Tomé and Príncipe Dobra (pre-2018)',
  stx: 'Stox',
  svc: 'Salvadoran Colón',
  syp: 'Syrian pound',
  szl: 'Swazi lilangeni',
  thb: 'Thai baht',
  theta: 'Theta',
  tjs: 'Tajikistani somoni',
  tmt: 'Turkmenistani manat',
  tnd: 'Tunisian dinar',
  top: 'Tongan Paʻanga',
  trx: 'TRON',
  try: 'Turkish lira',
  ttd: 'Trinidad & Tobago Dollar',
  ttt: 'Tap Project',
  tusd: 'True USD',
  twd: 'New Taiwan dollar',
  tzs: 'Tanzanian shilling',
  uah: 'Ukrainian hryvnia',
  ugx: 'Ugandan shilling',
  uni: 'Universe',
  usd: 'United States dollar',
  usdc: 'USD Coin',
  usdp: 'USDP Stablecoin',
  usdt: 'Tether',
  uyu: 'Uruguayan peso',
  uzs: 'Uzbekistani som',
  vet: 'Vechain',
  vnd: 'Vietnamese dong',
  vuv: 'Vanuatu vatu',
  waves: 'Waves',
  wbtc: 'Wrapped Bitcoin',
  wemix: 'WEMIX',
  wst: 'Samoan tala',
  xaf: 'Central African CFA franc',
  xag: 'Silver Ounce',
  xau: 'XauCoin',
  xcd: 'East Caribbean dollar',
  xdc: 'XDC Network',
  xdr: 'Special Drawing Rights',
  xec: 'Eternal Coin',
  xem: 'NEM',
  xlm: 'Stellar',
  xmr: 'Monero',
  xof: 'West African CFA franc',
  xpf: 'CFP franc',
  xrp: 'XRP',
  xtz: 'Tezos',
  yer: 'Yemeni rial',
  zar: 'South African rand',
  zec: 'ZCash',
  zil: 'Zilliqa',
  zmk: 'Zambian kwacha',
  zmw: 'Zambian Kwacha',
  zwl: 'Zimbabwean Dollar',
};
