export const ocrLanguages = [
  { label: 'English', id: 'eng' },
  { label: 'Portuguese', id: 'por' },
  { label: 'Afrikaans', id: 'afr' },
  { label: 'Albanian', id: 'sqi' },
  { label: 'Amharic', id: 'amh' },
  { label: 'Arabic', id: 'ara' },
  { label: 'Assamese', id: 'asm' },
  { label: 'Azerbaijani', id: 'aze' },
  { label: 'Azerbaijani - Cyrillic', id: 'aze_cyrl' },
  { label: 'Basque', id: 'eus' },
  { label: 'Belarusian', id: 'bel' },
  { label: 'Bengali', id: 'ben' },
  { label: 'Bosnian', id: 'bos' },
  { label: 'Bulgarian', id: 'bul' },
  { label: 'Burmese', id: 'mya' },
  { label: 'Catalan; Valencian', id: 'cat' },
  { label: 'Cebuano', id: 'ceb' },
  { label: 'Central Khmer', id: 'khm' },
  { label: 'Cherokee', id: 'chr' },
  { label: 'Chinese - Simplified', id: 'chi_sim' },
  { label: 'Chinese - Traditional', id: 'chi_tra' },
  { label: 'Croatian', id: 'hrv' },
  { label: 'Czech', id: 'ces' },
  { label: 'Danish', id: 'dan' },
  { label: 'Dutch; Flemish', id: 'nld' },
  { label: 'Dzongkha', id: 'dzo' },
  { label: 'English, Middle (1100-1500)', id: 'enm' },
  { label: 'Esperanto', id: 'epo' },
  { label: 'Estonian', id: 'est' },
  { label: 'Finnish', id: 'fin' },
  { label: 'French', id: 'fra' },
  { label: 'French, Middle (ca. 1400-1600)', id: 'frm' },
  { label: 'Galician', id: 'glg' },
  { label: 'Georgian', id: 'kat' },
  { label: 'German', id: 'deu' },
  { label: 'German Fraktur', id: 'frk' },
  { label: 'Greek, Modern (1453-)', id: 'ell' },
  { label: 'Greek, Ancient (-1453)', id: 'grc' },
  { label: 'Gujarati', id: 'guj' },
  { label: 'Haitian; Haitian Creole', id: 'hat' },
  { label: 'Hebrew', id: 'heb' },
  { label: 'Hindi', id: 'hin' },
  { label: 'Hungarian', id: 'hun' },
  { label: 'Icelandic', id: 'isl' },
  { label: 'Indonesian', id: 'ind' },
  { label: 'Inuktitut', id: 'iku' },
  { label: 'Irish', id: 'gle' },
  { label: 'Italian', id: 'ita' },
  { label: 'Japanese', id: 'jpn' },
  { label: 'Javanese', id: 'jav' },
  { label: 'Kannada', id: 'kan' },
  { label: 'Kazakh', id: 'kaz' },
  { label: 'Kirghiz; Kyrgyz', id: 'kir' },
  { label: 'Korean', id: 'kor' },
  { label: 'Kurdish', id: 'kur' },
  { label: 'Lao', id: 'lao' },
  { label: 'Latin', id: 'lat' },
  { label: 'Latvian', id: 'lav' },
  { label: 'Lithuanian', id: 'lit' },
  { label: 'Macedonian', id: 'mkd' },
  { label: 'Malay', id: 'msa' },
  { label: 'Malayalam', id: 'mal' },
  { label: 'Maltese', id: 'mlt' },
  { label: 'Marathi', id: 'mar' },
  { label: 'Nepali', id: 'nep' },
  { label: 'Norwegian', id: 'nor' },
  { label: 'Oriya', id: 'ori' },
  { label: 'Panjabi; Punjabi', id: 'pan' },
  { label: 'Persian', id: 'fas' },
  { label: 'Polish', id: 'pol' },
  { label: 'Pushto; Pashto', id: 'pus' },
  { label: 'Romanian; Moldavian; Moldovan', id: 'ron' },
  { label: 'Russian', id: 'rus' },
  { label: 'Sanskrit', id: 'san' },
  { label: 'Serbian', id: 'srp' },
  { label: 'Serbian - Latin', id: 'srp_latn' },
  { label: 'Sinhala; Sinhalese', id: 'sin' },
  { label: 'Slovak', id: 'slk' },
  { label: 'Slovenian', id: 'slv' },
  { label: 'Spanish; Castilian', id: 'spa' },
  { label: 'Swahili', id: 'swa' },
  { label: 'Swedish', id: 'swe' },
  { label: 'Syriac', id: 'syr' },
  { label: 'Tagalog', id: 'tgl' },
  { label: 'Tajik', id: 'tgk' },
  { label: 'Tamil', id: 'tam' },
  { label: 'Telugu', id: 'tel' },
  { label: 'Thai', id: 'tha' },
  { label: 'Tibetan', id: 'bod' },
  { label: 'Tigrinya', id: 'tir' },
  { label: 'Turkish', id: 'tur' },
  { label: 'Uighur; Uyghur', id: 'uig' },
  { label: 'Ukrainian', id: 'ukr' },
  { label: 'Urdu', id: 'urd' },
  { label: 'Uzbek', id: 'uzb' },
  { label: 'Uzbek - Cyrillic', id: 'uzb_cyrl' },
  { label: 'Vietnamese', id: 'vie' },
  { label: 'Welsh', id: 'cym' },
  { label: 'Yiddish', id: 'yid' },
];
