//这里id是tesseract OCR支持的语言，label是显示的英语，translation是翻译的本国语言
//为什么不公共化，因为这个文件这个id只有这个地方用到，不需要公共化，并且固定不变
export const ocrOfficialSupportLanguages = [
  { label: 'English', id: 'eng', translation: 'English' },
  { label: 'Portuguese', id: 'por', translation: 'Português' },
  { label: 'Afrikaans', id: 'afr', translation: 'Afrikaans' },
  { label: 'Albanian', id: 'sqi', translation: 'Shqip' },
  { label: 'Amharic', id: 'amh', translation: 'አማርኛ' },
  { label: 'Arabic', id: 'ara', translation: 'العربية' },
  { label: 'Assamese', id: 'asm', translation: 'অসমীয়া' },
  { label: 'Azerbaijani', id: 'aze', translation: 'Azərbaycan dili' },
  {
    label: 'Azerbaijani - Cyrillic',
    id: 'aze_cyrl',
    translation: 'Азәрбајҹан - Кирилица',
  },
  { label: 'Basque', id: 'eus', translation: 'Euskara' },
  { label: 'Belarusian', id: 'bel', translation: 'Беларуская' },
  { label: 'Bengali', id: 'ben', translation: 'বাংলা' },
  { label: 'Bosnian', id: 'bos', translation: 'Bosanski' },
  { label: 'Bulgarian', id: 'bul', translation: 'Български' },
  { label: 'Burmese', id: 'mya', translation: 'ဗမာစာ' },
  { label: 'Catalan; Valencian', id: 'cat', translation: 'Català' },
  { label: 'Cebuano', id: 'ceb', translation: 'Cebuano' },
  { label: 'Central Khmer', id: 'khm', translation: 'ភាសាខ្មែរ' },
  { label: 'Cherokee', id: 'chr', translation: 'ᏣᎳᎩ' },
  { label: 'Chinese - Simplified', id: 'chi_sim', translation: '简体中文' },
  { label: 'Chinese - Traditional', id: 'chi_tra', translation: '繁體中文' },
  { label: 'Croatian', id: 'hrv', translation: 'Hrvatski' },
  { label: 'Czech', id: 'ces', translation: 'Čeština' },
  { label: 'Danish', id: 'dan', translation: 'Dansk' },
  { label: 'Dutch; Flemish', id: 'nld', translation: 'Nederlands' },
  { label: 'Dzongkha', id: 'dzo', translation: 'རྫོང་ཁ' },
  {
    label: 'English, Middle (1100-1500)',
    id: 'enm',
    translation: 'English, Middle (1100-1500)',
  },
  { label: 'Esperanto', id: 'epo', translation: 'Esperanto' },
  { label: 'Estonian', id: 'est', translation: 'Eesti' },
  { label: 'Finnish', id: 'fin', translation: 'Suomi' },
  { label: 'French', id: 'fra', translation: 'Français' },
  {
    label: 'French, Middle (ca. 1400-1600)',
    id: 'frm',
    translation: 'Français, Moyen (ca. 1400-1600)',
  },
  { label: 'Galician', id: 'glg', translation: 'Galego' },
  { label: 'Georgian', id: 'kat', translation: 'ქართული' },
  { label: 'German', id: 'deu', translation: 'Deutsch' },
  { label: 'German Fraktur', id: 'frk', translation: 'Deutsch Fraktur' },
  {
    label: 'Greek, Modern (1453-)',
    id: 'ell',
    translation: 'Ελληνικά, Νέα (1453-)',
  },
  {
    label: 'Greek, Ancient (-1453)',
    id: 'grc',
    translation: 'Ελληνικά, Αρχαία (-1453)',
  },
  { label: 'Gujarati', id: 'guj', translation: 'ગુજરાતી' },
  {
    label: 'Haitian; Haitian Creole',
    id: 'hat',
    translation: 'Kreyòl ayisyen; Ayiti Chèlen',
  },
  { label: 'Hebrew', id: 'heb', translation: 'עברית' },
  { label: 'Hindi', id: 'hin', translation: 'हिन्दी' },
  { label: 'Hungarian', id: 'hun', translation: 'Magyar' },
  { label: 'Icelandic', id: 'isl', translation: 'Íslenska' },
  { label: 'Indonesian', id: 'ind', translation: 'Bahasa Indonesia' },
  { label: 'Inuktitut', id: 'iku', translation: 'ᐃᓄᒃᑎᑐᑦ' },
  { label: 'Irish', id: 'gle', translation: 'Gaeilge' },
  { label: 'Italian', id: 'ita', translation: 'Italiano' },
  { label: 'Japanese', id: 'jpn', translation: '日本語' },
  { label: 'Javanese', id: 'jav', translation: 'Basa Jawa' },
  { label: 'Kannada', id: 'kan', translation: 'ಕನ್ನಡ' },
  { label: 'Kazakh', id: 'kaz', translation: 'Қазақ тілі' },
  { label: 'Kirghiz; Kyrgyz', id: 'kir', translation: 'Кыргызча; Киргиз тили' },
  { label: 'Korean', id: 'kor', translation: '한국어' },
  { label: 'Kurdish', id: 'kur', translation: 'Kurdî' },
  { label: 'Lao', id: 'lao', translation: 'ລາວ' },
  { label: 'Latin', id: 'lat', translation: 'Latina' },
  { label: 'Latvian', id: 'lav', translation: 'Latviešu' },
  { label: 'Lithuanian', id: 'lit', translation: 'Lietuvių' },
  { label: 'Macedonian', id: 'mkd', translation: 'Македонски' },
  { label: 'Malay', id: 'msa', translation: 'Bahasa Melayu' },
  { label: 'Malayalam', id: 'mal', translation: 'മലയാളം' },
  { label: 'Maltese', id: 'mlt', translation: 'Malti' },
  { label: 'Marathi', id: 'mar', translation: 'मराठी' },
  { label: 'Nepali', id: 'nep', translation: 'नेपाली' },
  { label: 'Norwegian', id: 'nor', translation: 'Norsk' },
  { label: 'Oriya', id: 'ori', translation: 'ଓଡ଼ିଆ' },
  { label: 'Panjabi; Punjabi', id: 'pan', translation: 'ਪੰਜਾਬੀ; پنجابی' },
  { label: 'Persian', id: 'fas', translation: 'فارسی' },
  { label: 'Polish', id: 'pol', translation: 'Polski' },
  { label: 'Pushto; Pashto', id: 'pus', translation: 'پښتو' },
  {
    label: 'Romanian; Moldavian; Moldovan',
    id: 'ron',
    translation: 'Română; Moldovenească',
  },
  { label: 'Russian', id: 'rus', translation: 'Русский' },
  { label: 'Sanskrit', id: 'san', translation: 'संस्कृतम्' },
  { label: 'Serbian', id: 'srp', translation: 'Српски' },
  {
    label: 'Serbian - Latin',
    id: 'srp_latn',
    translation: 'Srpski - Latinica',
  },
  { label: 'Sinhala; Sinhalese', id: 'sin', translation: 'සිංහල' },
  { label: 'Slovak', id: 'slk', translation: 'Slovenčina' },
  { label: 'Slovenian', id: 'slv', translation: 'Slovenščina' },
  { label: 'Spanish; Castilian', id: 'spa', translation: 'Español' },
  { label: 'Swahili', id: 'swa', translation: 'Kiswahili' },
  { label: 'Swedish', id: 'swe', translation: 'Svenska' },
  { label: 'Syriac', id: 'syr', translation: 'ܣܘܪܝܬ' },
  { label: 'Tagalog', id: 'tgl', translation: 'Tagalog' },
  { label: 'Tajik', id: 'tgk', translation: 'Тоҷикӣ' },
  { label: 'Tamil', id: 'tam', translation: 'தமிழ்' },
  { label: 'Telugu', id: 'tel', translation: 'తెలుగు' },
  { label: 'Thai', id: 'tha', translation: 'ไทย' },
  { label: 'Tibetan', id: 'bod', translation: 'བོད་སྐད་' },
  { label: 'Tigrinya', id: 'tir', translation: 'ትግርኛ' },
  { label: 'Turkish', id: 'tur', translation: 'Türkçe' },
  { label: 'Uighur; Uyghur', id: 'uig', translation: 'ئۇيغۇرچە; ئۇيغۇر تىلى' },
  { label: 'Ukrainian', id: 'ukr', translation: 'Українська' },
  { label: 'Urdu', id: 'urd', translation: 'اردو' },
  { label: 'Uzbek', id: 'uzb', translation: 'Oʻzbekcha' },
  { label: 'Uzbek - Cyrillic', id: 'uzb_cyrl', translation: 'Ўзбекча - Кирил' },
  { label: 'Vietnamese', id: 'vie', translation: 'Tiếng Việt' },
  { label: 'Welsh', id: 'cym', translation: 'Cymraeg' },
  { label: 'Yiddish', id: 'yid', translation: 'ייִדיש' },
];
